name: Line Bot Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - .dockerignore
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}

jobs:
  update-line-rich-menu:
    name: Update Line rich menu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: "Install line-bot-sdk"
        run: 
          pip install line-bot-sdk==2.4.1

      - name: "Update Line rich menu"
        run: 
          python ./rich_menus/rich_menus_sdk.py

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only